// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lees.model;

import com.lees.model.CartDataOnDemand;
import com.lees.model.CartIntegrationTest;
import com.lees.repository.CartRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CartIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CartIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CartIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CartIntegrationTest: @Transactional;
    
    @Autowired
    private CartDataOnDemand CartIntegrationTest.dod;
    
    @Autowired
    CartRepository CartIntegrationTest.cartRepository;
    
    @Test
    public void CartIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        long count = cartRepository.count();
        Assert.assertTrue("Counter for 'Cart' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CartIntegrationTest.testFind() {
        Cart obj = dod.getRandomCart();
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide an identifier", id);
        obj = cartRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cart' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Cart' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CartIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        long count = cartRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Cart', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Cart> result = cartRepository.findAll();
        Assert.assertNotNull("Find all method for 'Cart' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Cart' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CartIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        long count = cartRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Cart> result = cartRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Cart' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Cart' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CartIntegrationTest.testFlush() {
        Cart obj = dod.getRandomCart();
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide an identifier", id);
        obj = cartRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Cart' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCart(obj);
        Integer currentVersion = obj.getVersion();
        cartRepository.flush();
        Assert.assertTrue("Version for 'Cart' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CartIntegrationTest.testSaveUpdate() {
        Cart obj = dod.getRandomCart();
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide an identifier", id);
        obj = cartRepository.findOne(id);
        boolean modified =  dod.modifyCart(obj);
        Integer currentVersion = obj.getVersion();
        Cart merged = cartRepository.save(obj);
        cartRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Cart' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CartIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        Cart obj = dod.getNewTransientCart(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Cart' identifier to be null", obj.getId());
        cartRepository.save(obj);
        cartRepository.flush();
        Assert.assertNotNull("Expected 'Cart' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CartIntegrationTest.testDelete() {
        Cart obj = dod.getRandomCart();
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide an identifier", id);
        obj = cartRepository.findOne(id);
        cartRepository.delete(obj);
        cartRepository.flush();
        Assert.assertNull("Failed to remove 'Cart' with identifier '" + id + "'", cartRepository.findOne(id));
    }
    
}
